# Generated by Django 5.2.17 on 2026-09-06 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_courses', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('minimum_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maximum_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('other_criteria', models.TextField(blank=True)),
                ('scholarship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='scholarships.scholarship')),
            ],
        ),
    ]
