# Generated by Django 5.2.17 on 2026-09-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarshipeligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('MARKSHEET', 'Marksheet'), ('INCOME_CERTIFICATE', 'Income Certificate'), ('CASTE_CERTIFICATE', 'Caste Certificate'), ('ADMISSION_PROOF', 'Admission Proof'), ('FEE_RECEIPT', 'Fee Receipt'), ('BANK_PROOF', 'Bank Account Proof'), ('OTHER', 'Other')], max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='scholarships.scholarship')),
            ],
        ),
    ]
