# Generated by Django 5.2.17 on 2026-09-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('scholarships', '0003_scholarshiprequireddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='providers.providerprofile'),
        ),
    ]
