# Generated by Django 5.2.17 on 2026-09-07 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('scholarships', '0004_alter_scholarship_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'scholarship'), name='unique_student_scholarship_application'),
        ),
    ]
