# Generated by Django 5.2.17 on 2026-09-07 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('MARKSHEET', 'Marksheet'), ('INCOME_CERTIFICATE', 'Income Certificate'), ('CASTE_CERTIFICATE', 'Caste Certificate'), ('ADMISSION_PROOF', 'Admission Proof'), ('FEE_RECEIPT', 'Fee Receipt'), ('BANK_PROOF', 'Bank Account Proof'), ('OTHER', 'Other')], max_length=50)),
                ('document', models.FileField(upload_to='student_documents/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
