# Generated by Django 5.2.17 on 2026-09-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_unique_student_scholarship_application'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application'),
        ),
    ]
